０６１０本もの/sanada_kazuyuki/src/chapter6/beans/Message.java
package chapter6.beans;

import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable {
    private static final long serialVersionUID = 1L;

    private int id;
    private int user_id;
    private String Category;
    private String text;
    private String title;
    private int is_delete;
    private Date createdDate;
    private Date updatedDate;

    public int getDelete() {
		return is_delete;
	}
	public void setDelete(int is_delete) {
		this.is_delete = is_delete;
	}
    public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public int getUser_id() {
		return user_id;
	}
	public void setUser_id(int user_id) {
		this.user_id = user_id;
	}
	public String getCategory() {
		return Category;
	}
	public void setCategory(String Category) {
		this.Category = Category;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}

０６１０本もの/sanada_kazuyuki/src/chapter6/beans/UserMessage.java
package chapter6.beans;

import java.io.Serializable;
import java.util.Date;

public class UserMessage implements Serializable {
    private static final long serialVersionUID = 1L;

    private int id;
    private int user_id;
    private String user_name;
    private String Category;
    private String text;
    private String title;
    private String Branch;
    private int is_delete;
    private Date createdDate;
    private Date updatedDate;

	public int getIs_delete() {
		return is_delete;
	}
	public void setIs_delete(int is_delete) {
		this.is_delete = is_delete;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public int getUser_id() {
		return user_id;
	}
	public void setUser_id(int user_id) {
		this.user_id = user_id;
	}
	public String getUser_name() {
		return user_name;
	}
	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}
	public String getBranch() {
		return Branch;
	}
	public void setBranch(String Branch) {
		this.Branch = Branch;
	}
	public String getCategory() {
		return Category;
	}
	public void setCategory(String Category) {
		this.Category = Category;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}

０６１０本もの/sanada_kazuyuki/src/chapter6/controller/LoginServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import chapter6.beans.User;
import chapter6.service.LoginService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        request.getRequestDispatcher("login.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        String accountOrUser_name = request.getParameter("accountOrUser_name");
        String password = request.getParameter("password");

        LoginService loginService = new LoginService();
        User user = loginService.login(accountOrUser_name, password);

        HttpSession session = request.getSession();
        if (user != null) {

            session.setAttribute("loginUser", user);
            response.sendRedirect("./");
        } else {

            List<String> messages = new ArrayList<String>();
            messages.add("ログインに失敗しました。");
            session.setAttribute("errorMessages", messages);
            response.sendRedirect("login");
        }
    }

}

０６１０本もの/sanada_kazuyuki/src/chapter6/controller/SettingsServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.User;
import chapter6.exception.NoRowsUpdatedRuntimeException;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/settings" })
public class SettingsServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws ServletException, IOException {

        HttpSession session = request.getSession();
        //セッションよりログインユーザーの情報を取得
        User loginUser = (User) session.getAttribute("loginUser");
        //ログインユーザー情報のidを元にDBからユーザー情報取得
        User editUser = new UserService().getUser(loginUser.getUser_id());
        request.setAttribute("editUser", editUser);

        request.getRequestDispatcher("settings.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws ServletException, IOException {

        List<String> messages = new ArrayList<String>();
        HttpSession session = request.getSession();
        User editUser = getEditUser(request);

        if (isValid(request, messages) == true) {

            try {
                new UserService().update(editUser);
            } catch (NoRowsUpdatedRuntimeException e) {
                messages.add("他の人によって更新されています。最新のデータを表示しました。データを確認してください。");
                session.setAttribute("errorMessages", messages);
                request.setAttribute("editUser", editUser);
                request.getRequestDispatcher("settings.jsp").forward(request, response);
                return;
            }

            session.setAttribute("loginUser", editUser);

            response.sendRedirect("./");
        } else {
            session.setAttribute("errorMessages", messages);
            request.setAttribute("editUser", editUser);
            request.getRequestDispatcher("settings.jsp").forward(request, response);
        }
    }

    private User getEditUser(HttpServletRequest request)
            throws IOException, ServletException {

        User editUser = new User();
        editUser.setUser_id(Integer.parseInt(request.getParameter("user_id")));
        editUser.setUser_name(request.getParameter("user_name"));
        editUser.setBranch(request.getParameter("Branch"));
        editUser.setPassword(request.getParameter("password"));
        editUser.setDepartment_office(request.getParameter("Department_office"));
        return editUser;
    }


    private boolean isValid(HttpServletRequest request, List<String> messages) 
    {

        String user_name = request.getParameter("user_name");
        String password = request.getParameter("password");
        String Branch = request.getParameter("Branch");
        String Department_office = request.getParameter("Department_office");

        if (StringUtils.isEmpty(user_name) == true) {
            messages.add("アカウント名を入力してください");
        }
        if (StringUtils.isEmpty(password) == true) {
            messages.add("パスワードを入力してください");
        }
        if (StringUtils.isEmpty(Branch) == true) {
            messages.add("支店を入力してください");
        }
        if (StringUtils.isEmpty(Department_office) == true) {
            messages.add("部署・役所を入力してください");
        }
          if (messages.size() == 0) {
            return true;
        } else {
            return false;
        }
    }

}

０６１０本もの/sanada_kazuyuki/src/chapter6/controller/SignUpServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.User;
//import chapter6.beans.User;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        request.getRequestDispatcher("signup.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response)throws IOException, ServletException {

        List<String> messages = new ArrayList<String>();

        HttpSession session = request.getSession();
        if (isValid(request, messages) == true) {

            User user = new User();
            user.setUser_name(request.getParameter("user_name"));
            user.setPassword(request.getParameter("password"));
            user.setBranch(request.getParameter("Branch"));
            user.setDepartment_office(request.getParameter("Department_office"));
          //  user.setDescription(request.getParameter("description"));
       //   user.setUser_Stop_revival (request.getParameter("user_Stop_revival"));


            new UserService().register(user);

            response.sendRedirect("./");
        } else {
            session.setAttribute("errorMessages", messages);
            response.sendRedirect("signup");
        }
    }

    private boolean isValid(HttpServletRequest request, List<String> messages) {
        String user_name = request.getParameter("user_name");
        String password = request.getParameter("password");
        String Branch = request.getParameter("Branch");
        String Department_office = request.getParameter("Department_office");


        if (StringUtils.isEmpty(user_name) == true) {
            messages.add("名称を入力してください");
        }
        if (StringUtils.isEmpty(password) == true) {
            messages.add("パスワードを入力してください");
        }
        if (StringUtils.isEmpty(Branch) == true) {
            messages.add("パスワードを入力してください");
        }
        if (StringUtils.isEmpty(Department_office) == true) {
            messages.add("部署・役職を入力してください");
        }
        // TODO アカウントが既に利用されていないか、メールアドレスが既に登録されていないかなどの確認も必要
        if (messages.size() == 0) {
            return true;
        } else {
            return false;
        }
    }

}

０６１０本もの/sanada_kazuyuki/src/chapter6/controller/TopServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import chapter6.beans.User;
import chapter6.beans.UserComments;
import chapter6.beans.UserMessage;
import chapter6.service.CommentsService;
import chapter6.service.MessageService;

@WebServlet(urlPatterns = { "/index.jsp" })
public class TopServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        User user = (User) request.getSession().getAttribute("loginUser");
        boolean isShowMessageForm;
        if (user != null) {
            isShowMessageForm = true;
        } else {
            isShowMessageForm = false;
        }

        List<UserMessage> messages = new MessageService().getMessage();

        request.setAttribute("messages", messages);
        request.setAttribute("isShowMessageForm", isShowMessageForm);

        List<UserComments> comments = new CommentsService().getComments();

        request.setAttribute("comments", comments);
      //  request.setAttribute("isShowMessageForm", isShowMessageForm);

        request.getRequestDispatcher("/top.jsp").forward(request, response);
    }
}

０６１０本もの/sanada_kazuyuki/WebContent/Newpost.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<!DOCTYPE html>
<html>
<head>

  <title>新規登録画面</title>
   <link href="./css/style.css" rel="stylesheet" type="text/css">
</head>

<!-- 画面タイトル -->
<div class="imui-title">
  <h1>新規登録画面</h1>

</div>

    <h2>入力フォーム</h2>

			<c:if test="${  empty loginUser }">
				<form action="login" method="post">
					<br /> <label for="accountOrUser_id"> ログインID</label> <input
						name="accountOrUser_id" id="accountOrUser_id" /> <br /> <label
						for="password">パスワード</label> <input name="password"
						type="password" id="password" /> <br /> <input type="submit"
						value="ログイン" /> <br />
				</form>
			</c:if>
			<c:if test="${ not empty loginUser }">
				<a href="./">ホーム</a>
				<br />
				<a href="signup.jsp">ユーザー新規登録画面</a>
				<br />
				<a href="logout">ログアウト</a>
				<br />


				<div class="profile">
					<div class="user_name">
						<h2>
							<c:out value="${loginUser.user_name}" />
						</h2>
					</div>
					<div class="user_id">
						<c:out value="${loginUser.branch}" />
					</div>
					<div class="user_id">
						<c:out value="${loginUser.description}" />
					</div>
				</div>

<div class="form-area">

					<form action="newMessage" method="post">

					    <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session" />
            </c:if>

<br><label for="title">タイトル<br />

<textarea name="title" cols="100" rows="1" maxlength="30" class="tweet-box"></textarea></label>
<br><label for="Category">カテゴリ<br />
<textarea name="Category" cols="50" rows="1" maxlength="10" class="tweet-box"></textarea></label>
<br><label for="text">新規投稿<br />
<textarea name="message" cols="100" rows="5" maxlength="1000" class="tweet-box"></textarea></label>
						<br />
						<input type="submit" value="投稿">(1000文字まで）
					</form>
					</div>
				</c:if>

	</body>
</html>

０６１０本もの/sanada_kazuyuki/WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
   <link href="./css/style.css" rel="stylesheet" type="text/css">
    <head>
    <body>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>ログイン</title>

    </head>
    	<h1>掲示板システム</h1>
	<hr>
<div align="left">

        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session"/>
            </c:if>

            <form action="login" method="post"><br />
                <label for=accountOrUser_name>アカウント名</label>
                <input name="accountOrUser_name" id="accountOrUser_name"/> <br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password"/> <br />

                <input type="submit" value="ログイン" /> <br />

            </form>

        </div>

         </div>

    </body>
</html>

０６１０本もの/sanada_kazuyuki/WebContent/settings.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<h1>ユーザー編集画面</h1>
	<hr>
    <head>

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>${loginUser.user_name}の設定</title>
        <link href="css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session"/>
            </c:if>
            	<a href="signup.jsp">ユーザー新規登録画面</a>
				<br />

            <form action="settings" method="post"><br />
                <input name="user_id" value="${editUser.user_id}" id="user_id" type="hidden"/>
                <label for="user_name">名称</label>
                <input name="user_name" value="${editUser.user_name}" id="user_name"/>（名前はあなたの公開プロフィールに表示されます）<br />

                <label for="password">新パスワード</label>
                <input name="password" type="password" id="password"/> <br />

                <label for="Branch">支店</label>
                <input name="Branch" value="${editUser.branch}" id="Branch"/> <br />

                <label for="Department_office">部署・役所</label>
                 <input name="Department_office" value="${editUser.department_office}" id="Department_office"/> <br />

                <input type="submit" value="登録" /> <br />
                <a href="./">戻る</a>
            </form>

        </div>
    </body>
</html>

０６１０本もの/sanada_kazuyuki/WebContent/signup.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>ユーザー新規登録画面</title>
     <link href="./css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
    <h1>ユーザー新規登録画面</h1>
        <div class="main-contents">
            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                       <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session" />
            </c:if>
            <form action="signup" method="post">
                <br> <label for="user_name">名称</label> <input name="user_name" id="user_name" />
                 <br><label for="Branch">支店</label> <input name="Branch" id="Branch" /> <br />
                     <label for="password">パスワード</label> <input name="password" type="password" id="password" />
                      <br /> <label for="Department_office">部署・役職	</label> <input name="Department_office" id="Department_office" /> <br />


                <br /> <input type="submit" value="登録" /> <br /> <a href="./">戻る</a>
            </form>
        </div>
    </body>
</html>

０６１０本もの/sanada_kazuyuki/WebContent/top.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<title>ホーム</title>
<link href="./css/style.css" rel="stylesheet" type="text/css">
</head>
<body>
	<div class="header"></div>
	<h1>掲示板システム</h1>
	<hr>
	<div align="left">
		<c:if test="${  empty loginUser }">
			<br />
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="messages">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
			<form action="login" method="post">
				<br /> <label for="accountOrUser_name"> ログインID</label> <input
					name="accountOrUser_name" id="accountOrUser_name" /> <br /> <label
					for="password">パスワード</label> <input name="password" type="password"
					id="password" /> <br /> <input type="submit" value="ログイン" /> <br />
			</form>
		</c:if>
		<c:if test="${ not empty loginUser }">
			<a href="Newpost.jsp">新規投稿画面</a>
			<br />
			<a href="signup.jsp">ユーザー新規登録画面</a>
			<br />
			<a href="settings">ユーザー管理画面</a>
			<br />
			<a href="logout">ログアウト</a>
			<br />
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="messages">
						<c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />

			<div class="profile">
				<div class="user_name">
					<h2>
						<c:out value="${loginUser.user_name}" />
					</h2>
				</div>
				<div class="user_id">
					<c:out value="${loginUser.branch}" />
				</div>
				<div class="user_id">
					<c:out value="${loginUser.description}" />
				</div>
			</div>
		</c:if>



		<div class="messages">
			<c:forEach items="${messages}" var="message">
				<div class="message">
					<div class="account-name">
			<c:if test="${ message.is_delete == 0 }">
						件名：
						<c:out value="${message.title}" />
						<br /> 名前：
						<c:out value="${message.user_name}" />
						<br /> カテゴリ：
						<c:out value="${message.category}" />
						<hr>
						<div class="text">
							<c:out value="${message.text}" />
						</div>
						<div class="date">
							<fmt:formatDate value="${message.createdDate}"
								pattern="yyyy/MM/dd HH:mm:ss" />
						</div>

					<form action="delete" method="post">
									<input type="hidden" name="is_delete"value="1" >
									<input type="hidden" name="id"value="${message.id}" >
										<input type="submit" value="投稿を削除">
		</form>

						<hr>

						<div class="comments">
							<c:forEach items="${comments}" var="comment">
								<c:if test="${comment.message_id == message.id && comment.is_delete == 0 }">
									<div class="comment">
										<hr>
										名前：
										<c:out value="${comment.user_name}" />
										<br /> コメント：
										<c:out value="${comment.comments}" />
									</div>
									<div class="date">
										<fmt:formatDate value="${comment.createdDate}"
											pattern="yyyy/MM/dd HH:mm:ss" />
									</div>
									<c:if test="${loginUser.user_id == comment.user_id}">




									<form action="commentdelete" method="post">
									<input type="hidden" name='is_delete'value=1 >
									<input type="hidden" name='id'value="${comment.id }" >
										<input type="submit" value="コメントを削除">
									</form>
									</c:if>

						</c:if>

							</c:forEach>
						</div>
						<div class="form-area">


							<c:if test="${ isShowMessageForm }">
								<form action=comments method="post">
									コメント<br />
									<textarea name="comments" cols="10" rows="5" maxlength="500"
										class="tweet-box"></textarea>
									<br /> <input type="hidden" name="message_id"
										value="${message.id}" /> <input type="submit" value="投稿">（500文字まで）
								</form>
								<hr>
							</c:if>
						</div>
							</c:if>
					</div>
				</div>

			</c:forEach>
		</div>
	</div>
</body>
</html>